version: '3'

services:
  gateway:
    image: korobosta/koro-erp-gateway
    env_file:
      - ./config/.env
      - ./config/.env.gateway
    ports:
      - "7009:7009"

  hrm:
    image: korobosta/koro-erp-hrm
    env_file:
      - ./config/.env
      - ./config/.env.hrm
    ports:
      - "7001:7001"

  logs:
    image: korobosta/koro-erp-logs
    env_file:
      - ./config/.env
      - ./config/.env.logs
    ports:
      - "7010:7010"
    volumes:
      - "../logs/logs:/root/logs"

  auth:
    image: korobosta/koro-erp-auth
    env_file:
      - ./config/.env
      - ./config/.env.auth
    ports:
      - "7000:7000"
